name: wfA

on:
  push:
    branches:
      - main
      - feature/*

    paths:
      - 'webAppcode/**'
      - '.github/workflows/workflowA.yml'
      - '.github/workflows/workflowB.yml'

  workflow_dispatch:
  pull_request:
    branches:
      - main
      - feature/*


permissions:
  contents: read
  id-token: write
  pull-requests: write
  issues: write
  checks: write
  actions: read
  
jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}/webAppcode

  deploy:
    uses: ./.github/workflows/workflowAa.yml
    needs: jobA