name: wfA

on:
  push:
    branches:
      - main
      - feature/*

    paths:
      - 'webAppcode/**'
      - '.github/workflows/workflowA.yml'
      - '.github/workflows/workflowB.yml'

  workflow_dispatch:
  pull_request:
    branches:
      - main
      - feature/*

env:
  setuppath: 'webAppcode/fiyin/dare/config'
  configfile: 'config_ws_dev.json'

permissions:
  contents: read
  id-token: write
  pull-requests: write
  issues: write
  checks: write
  
jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Conver json to Variables
        run: |
          JSON_FILE=${{ env.setuppath }}/${{ env.configfile }}
          PREFIX="config"
          while IFS="=" read -r key value; do
            sanitized_key=$(echo $key | tr '[:lower:]' '[:upper:]'| tr -cd '[:alnum:]_')
            echo "${PREFIX}${sanitized_key}=${value}" >> $GITHUB_ENV
          done < <(jq -r 'to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]' $JSON_FILE)

      # - name: test Variables
      #   run: |
      #     cat ${{env.setuppath}}/${{config.model_name}}
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}/webAppcode

  deploy:
    uses: ./.github/workflows/workflowAa.yml
    needs: jobA