
name: deploys
on:
  workflow_call:

permissions:
  contents: read
  id-token: write
  
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          name: my-artifact1
          run-id: 10275847165

      

