
name: deploys
on:
  workflow_call:

permissions:
  contents: read
  id-token: write
  actions: read
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact1

      

